// AgentJS generates this complete SVG document. A browser only rasterizes the
// resulting vector markup; no DOM, Canvas, or WebGL API is used by the engine.
var agents = [
    { name: "Planner", role: "Task routing", usage: 82, latency: 18, color: "#8b5cf6" },
    { name: "Coder", role: "Native pipeline", usage: 67, latency: 31, color: "#22d3ee" },
    { name: "Reviewer", role: "Quality gate", usage: 94, latency: 12, color: "#34d399" }
];

var width = 1000;
var height = 620;
var total = 0;
for (var i = 0; i < agents.length; i++) total += agents[i].usage;
var average = Math.round(total / agents.length);

var svg =
    '<svg xmlns="http://www.w3.org/2000/svg" width="' + width + '" height="' + height +
    '" viewBox="0 0 ' + width + ' ' + height + '">' +
    '<defs>' +
      '<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">' +
        '<stop offset="0" stop-color="#111827"/><stop offset="1" stop-color="#020617"/>' +
      '</linearGradient>' +
      '<filter id="glow"><feGaussianBlur stdDeviation="7" result="blur"/>' +
        '<feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>' +
      '<style>text{font-family:Segoe UI,Arial,sans-serif}.muted{fill:#94a3b8}.label{fill:#e2e8f0}</style>' +
    '</defs>' +
    '<rect width="1000" height="620" rx="28" fill="url(#bg)"/>' +
    '<circle cx="900" cy="60" r="180" fill="#2563eb" opacity=".10"/>' +
    '<circle cx="90" cy="590" r="150" fill="#7c3aed" opacity=".10"/>' +
    '<text x="56" y="72" fill="#f8fafc" font-size="32" font-weight="700">AgentJS Runtime</text>' +
    '<text x="56" y="102" class="muted" font-size="15">Native JavaScript execution · live workload snapshot</text>' +
    '<rect x="784" y="48" width="160" height="46" rx="23" fill="#052e2b" stroke="#10b981" stroke-opacity=".5"/>' +
    '<circle cx="812" cy="71" r="6" fill="#34d399" filter="url(#glow)"/>' +
    '<text x="830" y="77" fill="#a7f3d0" font-size="16" font-weight="600">ALL SYSTEMS GO</text>' +
    '<rect x="56" y="136" width="888" height="112" rx="18" fill="#0f172a" stroke="#1e293b"/>' +
    '<text x="84" y="172" class="muted" font-size="13">ACTIVE AGENTS</text>' +
    '<text x="84" y="220" fill="#f8fafc" font-size="38" font-weight="700">' + agents.length + '</text>' +
    '<line x1="284" y1="160" x2="284" y2="224" stroke="#334155"/>' +
    '<text x="324" y="172" class="muted" font-size="13">AVERAGE LOAD</text>' +
    '<text x="324" y="220" fill="#f8fafc" font-size="38" font-weight="700">' + average + '%</text>' +
    '<line x1="584" y1="160" x2="584" y2="224" stroke="#334155"/>' +
    '<text x="624" y="172" class="muted" font-size="13">ENGINE</text>' +
    '<text x="624" y="218" fill="#60a5fa" font-size="27" font-weight="700">NATIVE VM</text>';

for (var j = 0; j < agents.length; j++) {
    var agent = agents[j];
    var y = 290 + j * 94;
    var barWidth = Math.round(agent.usage * 5.1);
    svg +=
        '<g>' +
          '<circle cx="76" cy="' + (y + 25) + '" r="20" fill="' + agent.color + '" opacity=".18"/>' +
          '<circle cx="76" cy="' + (y + 25) + '" r="7" fill="' + agent.color + '"/>' +
          '<text x="112" y="' + (y + 18) + '" class="label" font-size="18" font-weight="650">' + agent.name + '</text>' +
          '<text x="112" y="' + (y + 41) + '" class="muted" font-size="13">' + agent.role + '</text>' +
          '<rect x="300" y="' + (y + 10) + '" width="510" height="30" rx="15" fill="#1e293b"/>' +
          '<rect x="300" y="' + (y + 10) + '" width="' + barWidth + '" height="30" rx="15" fill="' + agent.color + '" opacity=".88"/>' +
          '<text x="832" y="' + (y + 31) + '" fill="#f8fafc" font-size="18" font-weight="700">' + agent.usage + '%</text>' +
          '<text x="900" y="' + (y + 31) + '" class="muted" font-size="13">' + agent.latency + ' ms</text>' +
        '</g>';
}

svg +=
    '<line x1="56" y1="574" x2="944" y2="574" stroke="#1e293b"/>' +
    '<text x="56" y="602" class="muted" font-size="13">JS → Lexer → Parser → Bytecode → VM → SVG</text>' +
    '<text x="944" y="602" text-anchor="end" fill="#64748b" font-size="13">Generated by AgentJS</text>' +
    '</svg>';

console.log(svg);

